# Generated by Django 5.0.6 on 2024-07-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_post_likes_user_liked_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
